### ISSUE TITLE
 class UnpicklerWrapper(pickle_module.Unpickler):  # type: ignore[name-defined]

### ISSUE THREAD

**Issue by weiguangzhao** [ferjad/3DCZSL#3]
When I load the pre-trained model, I got this error:

```
2022-11-28 18:42:05,529 shaper.train INFO: Loading checkpoint from pretrain/model_best_comp.pth, MD5: 1c91c6cd44a92e4701066a2262e187c8
Traceback (most recent call last):
  File "/data1/weiguang/project/3dzs/shaper/train_part_cls.py", line 499, in <module>
    main()
  File "/data1/weiguang/project/3dzs/shaper/train_part_cls.py", line 496, in main
    train(cfg, cfg.ZERO_SHOT, output_dir)
  File "/data1/weiguang/project/3dzs/shaper/train_part_cls.py", line 304, in train
    feat_checkpoint_data = feat_checkpointer.load(cfg.MODEL.WEIGHT, resume=cfg.AUTO_RESUME, resume_states=cfg.RESUME_STATES)
  File "/data1/weiguang/project/3dzs/shaper/../core/utils/checkpoint.py", line 54, in load
    checkpoint = self._load_file(f)
  File "/data1/weiguang/project/3dzs/shaper/../core/utils/checkpoint.py", line 102, in _load_file
    return torch.load(f, map_location=torch.device('cpu'), pickle_module=pickle)
  File "/data1/weiguang/.conda/envs/3dzs/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/data1/weiguang/.conda/envs/3dzs/lib/python3.8/site-packages/torch/serialization.py", line 869, in _load
    class UnpicklerWrapper(pickle_module.Unpickler):  # type: ignore[name-defined]
TypeError: the first argument must be callable
```

My envs are the following: RTX3090 pytorch=1.9.0 cuda=11.1 python=3.8
Maybe a pre-trained model without pickle is a solution.

**Comment by ferjad** [comment]
Your PyTorch version is newer than ours. There are pickle related updates in newer version of PyTorch which breaks compatibility with old ckpts. Our model is trained with PyTorch 1.7.1.

**Comment by weiguangzhao** [comment]
Oh, that is bad news.  RTX3090 only supports 1.9.0 and higher version PyTorch. 
By the way,  when I train the part_seg, I find it is a little slow. How many hours did you take to train it roughly(120 epochs)? Seemly it spends more time on the data process (on CPU), any information is helpful, thank you!

**Comment by ferjad** [comment]
I think you can still use a conda environment to install PyTorch 1.7.1 and write the state-dict to a non pickle format and load that in PyTorch 1.9. 
It took 3 days for training DCC on a A100 40GB GPU. This assumes you have a good pointnet backbone. 
I will recommend you export the weights to be compatible with PyTorch 1.9 and use model_best_comp.pth checkpoint in the root folder of our release as the backbone weights to train DCC.
Regarding training speed, if you have sufficient ram, turn the cache mode on. It loads the whole dataset to the RAM so the read speeds are instant.

**Comment by weiguangzhao** [comment]
Thanks for your help. For pytorch1.9, rewriting the code of loading the pre-trained model works for me.
